---
galaxy_info:
  author: Klaas Demter
  description: Role to configure Microsoft package repo.

  license: GPL-3.0-or-later

  min_ansible_version: 2.15.0

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - linux
    - system
    - ansible
    - microsoft
    - azure

dependencies: []
collections: []
...
