trigger:
- master

jobs:
- job: CG
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'Medium'
      failOnAlert: true

- job: Windows
  pool:
    vmImage: "windows-2019"

  steps:
    - task: CredScan@2
      inputs:
        toolMajorVersion: 'V2'

    - task: PostAnalysis@1
      inputs:
        AllTools: false
        APIScan: false
        BinSkim: false
        CodesignValidation: false
        CredScan: true
        FortifySCA: false
        FxCop: false
        ModernCop: false
        PoliCheck: false
        RoslynAnalyzers: false
        SDLNativeRules: false
        Semmle: false
        TSLint: false
        ToolLogsNotFoundAction: 'Standard'
