trigger:
  batch: true
  branches:
    include:
    - "*"

jobs:
- job: CG
  pool:
    name: pool-ubuntu-2004

  steps:
  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'Medium'
      failOnAlert: true

- job: CredScan
  pool:
    vmImage: "windows-2019"

  steps:
    - task: ea576cd4-c61f-48f8-97e7-a3cb07b90a6f@2
      inputs:
        toolMajorVersion: 'V2'
        suppressionsFile: 'CredScanSuppressions.json'

    - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
      inputs:
        AllTools: false
        APIScan: false
        BinSkim: false
        CodesignValidation: false
        CredScan: true
        FortifySCA: false
        FxCop: false
        ModernCop: false
        PoliCheck: false
        RoslynAnalyzers: false
        SDLNativeRules: false
        Semmle: false
        TSLint: false
        ToolLogsNotFoundAction: 'Standard'
