trigger:
  batch: true
  branches:
    include:
    - "*"

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'Medium'
    failOnAlert: true