---
galaxy_info:
  author: Bill Peck and Klaas Demter
  description: Role to setup ARC on an existing host.

  license: GPL-3.0-or-later

  min_ansible_version: 2.15.0

  # Supported platforms: see https://learn.microsoft.com/en-us/azure/azure-arc/servers/prerequisites#supported-operating-systems for Azure Arc supported Linux distributions.

  galaxy_tags:
    - linux
    - system
    - ansible
    - microsoft
    - azure
    - arc

dependencies: []
collections: []
...
