name: Run RedHat partner certification checker

permissions:
  contents: read

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

concurrency:
  group: cert-ver-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  call:
    uses: ansible-collections/partner-certification-checker/.github/workflows/certification-reusable.yml@a930fadb8b6799461bbbbce27b669f83e877fafa
